TELEGRAM_BOT_TOKEN = "7941979379:AAEWGtlb87RYkvht8GzL8Ber29uosKo3e4s"  # Token Bot kamu
TELEGRAM_CHAT_ID = "5721363432"             # ID chat/channel kamu
OPENROUTER_API_KEY = "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"              # API Key dari openrouter.ai
